### PR TITLE
Redirect from pilot.pdco to app.pdco

### PR DESCRIPTION
**Pull request by jasonaowen**
Configure Netlify to redirect requests.

Netlify allows [redirects between the domains of an app](https://docs.netlify.com/domains-https/custom-domains/multiple-domains/#domain-redirects) by using the [`_redirects` file](https://docs.netlify.com/routing/redirects/redirect-options/#domain-level-redirects).

This should not be merged until DNS is configured and confirmed working!

Issue #333 Change subdomain from pilot to app

### CODE REVIEW

**Comment by jasonaowen** [comment]
Unfortunately, I don't think we'll be able to test this change! We can take some assurance from the [redirect rules status check](https://github.com/PhilanthropyDataCommons/front-end/pull/420/checks?check_run_id=18874585467), which says:

> Successful in 42s — 1 redirect rule processed

> All redirect rules processed without errors.

and the Netlify deploy log which says the same. Since only redirects to `pilot.pdco` will trigger the redirection, I think we'll just have to test it once it's been deployed and adjust from there.

**Comment by jasonaowen** [comment]
The DNS changes are live, and I've marked `app.pdco` as the primary domain in Netlify. I believe this is ready to go!

**Review by reefdog — APPROVED** [review]
I do have one tiny request: can you add a line item to `RECENT_CHANGES.md`? It feels like a worthy bullet point! However, I also want to signal my approval otherwise, so I'm going to approve this… with my original approval message below.

-----

Huzzah! To reiterate your point, we kind of have to accept/merge this in order to see if it works… but it _looks_ correct and I'm cool with making it so.

On a recent call, I believe it was @jim-mcgowan who said most users won't even notice the change, so deploying without **first** notifying stakeholders doesn't feel like a violation of the spirit of https://github.com/PhilanthropyDataCommons/meta/issues/70. And since credentials are entered on a different domain entirely (`auth.pdco`), this won't even require people to fiddle with their password managers.

As far as I'm concerned, feel free to merge this when ready!

**Comment by jasonaowen** [comment]
Great catch, @reefdog! Thank you, updated and rebased.

**Comment by jasonaowen** [comment]
:facepalm: I did not read the [documentation on redirects](https://docs.netlify.com/routing/redirects/) correctly.

> Save a plain text file called `_redirects` without a file extension to the [publish directory](https://docs.netlify.com/configure-builds/overview/#definitions) of your site.

We had that already: https://github.com/PhilanthropyDataCommons/front-end/blob/c551844410d92a73507a76e30e9b68ec6ca90f6b/public/_redirects#L3

That's the rule that it was processing. The new file was ignored completely. Sorry, folks! I'll clean this up in a subsequent PR.

**Pull request merged**
